spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://ec2-174-129-209-212.compute-1.amazonaws.com:5432/d5ekmkp28glthn?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driver-class-name: org.postgresql.Driver
    username: jezgvyectjdxyk
    password: 0af2d5420681266f3e1663a9a1cb7fe09775030c6a416c562ccd6a253ce3b8df

logging:
  level:
    root: INFO
  file: heroapi.log